### PR TITLE
Added Spanish language and other changes to update things

### PR DESCRIPTION
**Pull request by perez987**
Thanks for this grateful app. 
I send this PR to have the app in Spanish.
If you don't want to merge the PR, for whatever reason, it's okay, I'm happy to use this app and to have it translated into Spanish. If it is the case, please tell me and close the PR.

Changes made:

- Added Spanish language. I have tried in the first place with `Localizable.strings` file but some strings have different length in English and Spanish and the UI presented several issues with truncated strings. That is why I have resorted to creating a Spanish `Main.storyboard`.
- `Whats New in macOS` was pointing to Big Sur, now it's updated to Ventura.
- Replaced the old Big Sur image with a new one of a more recent version of the app on Ventura.

I attach some screenshots so that you can see the appearance of the interface in Spanish.

1-General
2-Pantallas
3-Discos
4-Soporte

Note: To be able to run it on my PC I had to disable Xcode Automatic Sign, you have to re-enable it.

### CODE REVIEW

**Comment by 0xCUB3** [comment]
Wow, this is incredible! Did you use the latest commit and everything?

**Comment by perez987** [comment]
@0xCUB3 
Yes, got it today afternoon.

**Comment by perez987** [comment]
Good night. The word `Available` in the Storage tab was bothering me because it was the only string not translated into Spanish.
I have slightly modified the code in the HardwareCollector.swift file so that, before using Available, it checks what the main language code is, if it is `es` >> use `Disponible`, if not  use `Available`.
This is useful also if adding other languages.

```swift
        // Get the main language code (en for English, es for Spanish)
        var idioma = Bundle.main.preferredLocalizations[0]
        // print("Idioma : \(idioma)")  // for testing
        
        // If it's Spanish
        if idioma == "es" {
            return ["""
    \(name)
    \(size)(\(available)Disponible)
    """,String(1-percent)]
        }
        else { // If it isn't Spanish
            return ["""
    \(name)
    \(size)(\(available)Available)
    """,String(1-percent)]            
        }
```
available
disponible

Note that, even if a single file is modified, the Xcode project also changes other files automatically, so the PR shows a large number of files with changes but not really that many by me in a manual way.

**Comment by perez987** [comment]
@0xCUB3 
Sorry, I think I've messed up a bit with the images you have at the beginning of README.md, I wanted to leave only one but, when you look at it, configure it to your liking. Regards, Emilio.

**Comment by perez987** [comment]
@0xCUB3 
Both Display Preferences images are outdated, have the button on the right, I've changed them to current ones with the button centered.
They are changes that I make in my repo since I can't do it any other way, with my own images, of course you can accept them or not, or use your own images.
Either way, I really like this app and have really enjoyed working with it and learning new things.
And having it now in my own language 👍🏻

**Comment by MDNich** [comment]
Hey @perez987 co-coder here :) 

Glad you found this useful! Looks great to me. 

I will also try to put some localizations I can do such as FR-FR/CA/CH, RO.

**Comment by perez987** [comment]
Good morning @MDNich glad to read you.

**Comment by MDNich** [comment]
@perez987 see my pull request #19; contains your modifications too.

**Pull request closed without merging**
