### PR TITLE
Enable All Hardened Runtime + Signed with Developer Account

### PR DESCRIPTION
**Pull request by Am1nCmd**
I attach the new release that should fix quit unexpectedly 
image

### CODE REVIEW

**Comment by 0xCUB3** [comment]
@Am1nCmd the developer license fix will only work once since I don't have a paid apple developer account like you do. Since my app has been receiving a lot of traffic, Apple blacklisted apps signed by my Apple ID, including this specific app signed by any non-paid developer account. Sadly, I don't have any money so I can't pay for the license. You'll see that I mentioned this in #6 . Thanks for adding hardened runtime, though! I will implement it, though I can't merge because of the paid license thing.

**Comment by Am1nCmd** [comment]
If you want to continue your development, I can help you to sign it.

**Comment by 0xCUB3** [comment]
I would appreciate that, but I really can't accept the offer because that would require me to ask you to sign it for me on every release, and I don't feel good about having some stranger on the internet doing that for me. If there's some way for _me_ to sign it, then that would work better, but if it would require me taking time out of your life every time I need to make a release, I'd rather suffer the consequences until I get a job and can afford the developer license (I'm just a broke student right now)

**Comment by Am1nCmd** [comment]
Sad to hear that, why don't accept any donation then? If there a lot of user using this app I'm sure they want an update to make this app better too.

Anyway, is really up to you. I'm just giving advice.
Good luck

**Comment by 0xCUB3** [comment]
Hmm, I've never really put much thought into donation, since the project didn't really have any users until this summer...I might consider that, thanks! As for not pushing updates, that's mostly because I'm taking a lot of AP classes and generally difficult classes this semester, along with other extracurriculars, so my time to work on About This Hack and my other projects is limited. I'll try to get back into it sometime in late November/early December! Thanks for all the tips, advice, and offers! I appreciate it 👍

**Review by 0xCUB3 — APPROVED** [review]

**Comment by 0xCUB3** [comment]
@Am1nCmd I fixed it! This release should fix everything. Let me know if it still doesn't work. Download it from here:
https://github.com/0xCUB3/About-This-Hack/releases/tag/0.6.0

**Comment by Am1nCmd** [comment]
Awesome, I'll try to check on hackintosh and M1 today

**Pull request merged**
